; This file was auto-generated by drush make on May 17, 2016 by Nahuel
core = 8.x
api = 2

; Core
projects[drupal][version] = "8.1.8"

; By default, store all contrib modules in the "contrib" subdirectory of the
; modules directory.

defaults[projects][subdir] = "contrib"

; == Modules ==
; admin
projects[admin_toolbar][version] = "1.16"
projects[codesnippet][version] = "1.4"
projects[coffee][version] = "1.0-beta1"
; base
projects[ctools][version] = "3.0-alpha26"
projects[token][version] = "1.0-alpha2"
projects[pathauto][version] = "1.0-alpha3"
projects[metatag][version] = "1.0-beta9"
projects[honeypot][version] = "1.23"
projects[google_analytics][version] = "2.0"
projects[redirect][version] = "1.0-alpha1"
projects[contact_storage][version] = "1.0-beta4"
projects[dynamic_entity_reference][version] = "1.0-rc5"

projects[badge][type] = "module"
projects[badge][download][type] = "git"
projects[badge][download][url] = "https://git.drupal.org/sandbox/mnico/2773065.git"
projects[badge][download][branch] = "8.x-1.x"
projects[badge][download][revision] = "eab6e0e0a6eb05ab86c5d1851d4218605dc4c75d"
projects[badge][patch][] = "patches/0001-added-dynamic_entity_reference-dependency.patch"

; Themes
projects[omega][version] = "5.0-alpha7"
projects[omega][type] = "theme"

; Libraries
libraries[codesnippet][download][type] = "file"
libraries[codesnippet][download][url] = "http://download.ckeditor.com/codesnippet/releases/codesnippet_4.5.10.zip"
libraries[codesnippet][download][md5] = "2356335f99581524c4e45f42cec9e8a2"
