; This file was auto-generated by drush make on May 17, 2016 by Nahuel
core = 7.x
api = 2

; Core
projects[drupal][version] = "7.43"

; By default, store all contrib modules in the "contrib" subdirectory of the
; modules directory.

defaults[projects][subdir] = "contrib"


; Modules
projects[addressfield][version] = "1.2"
projects[addressfield_staticmap][version] = "1.0"
projects[admin_menu][version] = "3.0-rc5"
projects[adminimal_admin_menu][version] = "1.7"
projects[backup_migrate][version] = "3.1"
projects[ctools][version] = "1.9"
projects[ckeditor][version] = "1.17"
projects[codefilter][version] = "1.2"
projects[contact_google_analytics][version] = "1.4"
projects[date][version] = "2.9"
projects[diff][version] = "3.2"
projects[disqus][version] = "1.12"
projects[entity][version] = "1.7"
projects[entityreference][version] = "1.1"
projects[entityreference_prepopulate][version] = "1.6"
projects[features][version] = "2.8"
projects[flag][version] = "3.7"
projects[flexslider][version] = "2.0-rc1"
projects[flickr][version] = "1.8"
projects[ga_tokenizer][version] = "1.5"
projects[globalredirect][version] = "1.5"
projects[gmap][version] = "2.11"
projects[google_analytics][version] = "2.1"
projects[panels][version] = "3.5"
projects[l10n_update][version] = "1.1"
projects[libraries][version] = "2.2"
projects[link][version] = "1.4"
projects[masonry][version] = "2.0"
projects[masonry_views][version] = "1.0"
projects[metatag][version] = "1.13"
projects[panopoly_theme][version] = "1.32"
projects[path_breadcrumbs][version] = "3.3"
projects[pathauto][version] = "1.3"
projects[radix_layouts][version] = "3.4"
projects[redirect][version] = "1.0-rc3"
projects[rules][version] = "2.9"
projects[sharethis][version] = "2.12"
projects[strongarm][version] = "2.0"
projects[token][version] = "1.6"
projects[transliteration][version] = "3.2"
projects[views][version] = "3.13"
projects[views_fluid_grid][version] = "3.0"
projects[views_responsive_grid][version] = "1.3"
projects[xmlsitemap][version] = "2.2"

; Themes
projects[omega][version] = "4.3"

; creo que esto era por el theme, y parece que es camaleon, si carga bien, se puede borrar este bloque
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
;projects[fatal: Not a git repository (or any parent up to mount point ][download][type] = ""
;projects[fatal: Not a git repository (or any parent up to mount point ][download][url] = ""
;projects[fatal: Not a git repository (or any parent up to mount point ][type] = "theme"


; las copié feamente a mano libraries por ahora
; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
;libraries[ckeditor][download][type] = ""
;libraries[ckeditor][download][url] = ""
;libraries[ckeditor][directory_name] = "ckeditor"
;libraries[ckeditor][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
;libraries[colorbox][download][type] = ""
;libraries[colorbox][download][url] = ""
;libraries[colorbox][directory_name] = "colorbox"
;libraries[colorbox][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
;libraries[flexslider][download][type] = ""
;libraries[flexslider][download][url] = ""
;libraries[flexslider][directory_name] = "flexslider"
;libraries[flexslider][type] = "library"

