<?php

/**
* Implements hook_block_info().
*/

function common_blocks_block_info() {

  $blocks = array();
  $blocks['common_blocks'] = array(
    'info' => t('Copyright'),
  );
  $blocks['common_blocks_social'] = array(
    'info' => t('Redes sociales'),
  );
  return $blocks;
}

/**
* Implements hook_block_view().
*/

function common_blocks_block_view($delta = '') {

  $block = array();
  switch ($delta) {
    case 'common_blocks':
      $block['subject'] = '';
      $block['content'] = _common_blocks_content();
      break;

    case 'common_blocks_social':
      $block['subject'] = '';
      $block['content'] = _common_blocks_content_social();
      break;
  }
  return $block;
}

function _common_blocks_content() {

  $output = '<div>© 2007–2014, LLC. All rights reserved.</div>';

  return $output;

}

function _common_blocks_content_social() {

  $output = '<ul>
  <li><a href="https://groups.drupal.org/chile" target="_blank" title="Comunidad en Drupal Groups"><i class="fa fa-drupal"></i> Drupal Groups</a><li>
  <li><a href="https://www.flickr.com/groups/drupalchile/" target="_blank" title="Grupo en Flickr"><i class="fa fa-flickr"></i> Flickr</a></li>
  <li><a href="https://github.com/DrupalChile" target="_blank" title="Organización en GitHub"><i class="fa fa-github-square"></i> GitHub</a></li>
  <li><a href="http://www.meetup.com/Drupal-Chile" target="_blank" title="Grupo en Meetup"><i class="fa fa-calendar"></i> Meetup</a></li>
  <li><a href="https://twitter.com/drupalcl" target="_blank" title="Perfil en Twitter"><i class="fa fa-twitter-square"></i> Twitter</a></li>
  </ul>';

  return $output;

}



