<?php

/**
* Implements hook_block_info().
*/

function drupalcl_mobile_menu_block_info() {

  $blocks = array();
  $blocks['drupalcl_mobile_menu'] = array(
    'info' => t('Mobile menu'),
  );

  return $blocks;
}

/**
* Implements hook_block_view().
*/

function drupalcl_mobile_menu_block_view($delta = '') {

  $block = array();

  switch ($delta) {

    case 'drupalcl_mobile_menu':

      $block['subject'] = '';
      $block['content'] = '<div class="nav-mobile"><i class="fa fa-bars"></i></div>';
      break;
  }

  return $block;
}

// function _drupalcl_mobile_menu_code(){
//   $output = '<div class="nav-mobile"><i class="fa fa-bars"></i></div>';
//   return $output;
// }

