all:
  - language_interface
  - language_content
  - language_url
configurable:
  - language_interface
negotiation:
  language_content:
    enabled:
      language-interface: 0
  language_url:
    enabled:
      language-url: 0
      language-url-fallback: 1
  language_interface:
    enabled:
      language-user: -19
      language-selected: -15
    method_weights:
      language-user-admin: -20
      language-url: -18
      language-session: -17
      language-user: -19
      language-browser: -16
      language-selected: -15
_core:
  default_config_hash: dqouFqVseNJNvEjsoYKxbinFOITuCxYhi4y2OTNQP_8
langcode: es
