country:
  default: CL
first_day: 1
timezone:
  default: America/Santiago
  user:
    configurable: true
    warn: true
    default: 0
_core:
  default_config_hash: V9UurX2GPT05NWKG9f2GWQqFG2TRG8vczidwjpy7Woo
langcode: es
