name = Camaleón
description = A layout utilising the golden ratio (or camaleon proportion).
preview = preview.png
template = camaleon-layout

; Regions
regions[branding]       = Branding
regions[header]         = Header
regions[navigation]     = Navigation bar
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[slider]        = Slider
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer
regions[footer-bottom]         = Footer bottom

; Stylesheets
;stylesheets[all][] = css/layouts/divine/divine.layout.css
;stylesheets[all][] = css/layouts/divine/divine.layout.no-query.css
