<?php



/**
 * Implements hook_menu_alter().
 */
function drupalcl_menu_alter(&$items) {
  $items['node/%/issues']['access callback'] = 'drupalcl_access_node_proyect';
  $items['node/%/issues']['access arguments'] = array(1);
}


/**
 * Access callback.
 */
function drupalcl_access_node_proyect($nid) {
  if (is_numeric($nid) && ($node = node_load($nid))) {
    if ($node->type == 'proyecto') {
      return TRUE;
    }
  }

  return FALSE;
}


/**
 * Implements hook_module_implements_alter().
 */
function drupalcl_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'menu_alter') {
    $module = $implementations['drupalcl'];
    unset($implementations['drupalcl']);
    $implementations['drupalcl'] = $module;
  }
}


/**
 * Implements hook_views_api().
 */
function drupalcl_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'drupalcl') . '/views',
  );
}


/**
 * Implements hook_mail().
 */
function drupalcl_mail($key, &$message, $params) {

  $message['subject'] .= str_replace(array("\r", "\n"), '', $params['subject']);
  $message['body'][] = $params['message'];

  if ($key == 'bcc') {
    $message['headers'] += $params['headers'];
  }

}


/**
 * Send mail from Rules.
 */
function drupalcl_rules_action_send_mails($emails, $subject, $message, $from = NULL, $langcode, $settings, RulesState $state, RulesPlugin $element) {
  $emails = array_filter($emails, 'drupalcl_only_valid_email');

  $to = '';

  $Bcc = implode(', ', $emails);
  $from = !empty($from) ? str_replace(array("\r", "\n"), '', $from) : NULL;
  $params = array(
    'subject' => $subject,
    'message' => $message,
    'langcode' => $langcode,
    'headers' => array(
      'Bcc' => $Bcc,
    ),
  );

  $languages = language_list();
  $language = isset($languages[$langcode]) ? $languages[$langcode] : language_default();


  $message = drupal_mail('drupalcl', 'bcc', $to, $language, $params, $from);
  if ($message['result']) {
    watchdog('rules', 'Successfully sent email to %recipient', array('%recipient' => $Bcc));
  }
}


function drupalcl_only_valid_email($email) {
  return (is_string($email) && valid_email_address($email));
}



